package com.bb.bigbasketsalesapp.ui.fragments.profile.model

data class GetUserProfileModel(
    val Data: GetUserProfileData,
    val Output: String,
    val Message: String
)


data class GetUserProfileData(
    val ActionStatus: Boolean?=false,
    val ActiveFlag: Boolean,
    val BloodGroup: String,
    val Br_Id: Any,
    val BranchAddress: Any,
    val BranchCode: Any,
    val BranchId: Int,
    val BranchList: Any,
    val BranchListPOP: Any,
    val Branch_Id: Int,
    val Branch_Name: Any,
    val Count: Int,
    val CurrentPage: Int,
    val DOB: String,
    val DOJ: String,
    val DepartmentId: Int,
    val DepartmentList: Any,
    val DesignationName: String,
    val Designation_Id: Int,
    val DistrictList: Any,
    val DivisionDescription: String,
    val DivisionList: Any,
    val Division_Id: Int,
    val Division_Name: Any,
    val EmailId: Any,
    val EmpData: Any,
    val Emp_Dob: String,
    val Emp_Doj: String,
    val EmployeeName: String,
    val Employee_Id: Int,
    val Employeecode: String,
    val ExportList: Any,
    val FileName: Any,
    val Flag: String,
    val GSTIN: Any,
    val Gender: String,
    val MobileNo: Long,
    val ModelPrevilege: Any,
    val OrganisationId: Int,
    val OrganisationName: Any,
    val PageSize: Int,
    val RoleId: Int,
    val RoleLists: Any,
    val RoleName: Any,
    val SearchKeyWord: Any,
    val Session_Flag: Any,
    val StateId: Int,
    val StateList: Any,
    val UserId: Int,
    val EmployeePhoto:String,
    val User_Id: Int,
    val active_status: String,
    val dateofbrth: String,
    val dateofjoin: String,
    val genderList: Any,
    val statusvalue: Any
)